spring.datasource.url=jdbc:postgresql://dpg-d82ukge7r5hc73cp25s0-a:5432/spring_project_1cdb
spring.datasource.username=spring_project_1cdb_user
spring.datasource.password=RGBNtZifkNOzJ03pV2rLCzByM69EkwhP

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}